### ISSUE TITLE
pnpm workspaces only recognise overrides at the root package

### ISSUE THREAD

**Issue by ramirezj** [SocketDev/socket-cli#252]
Running `socket optimize` on a monorepo using pnpm workspaces results in (inconsistent) changes to nested `package.json` files, which are ignored

See: https://pnpm.io/package_json#pnpmoverrides

**Comment by jdalton** [comment]
@ramirezj The current behavior is to apply all overrides to the root and then to the workspace packages apply the overrides that apply to them so that when they are published others will get the overrides too. That is why the root is specified as `pnpm.overrides` and the workspaces packages get `resolutions` and `overrides` so that when published others consuming the packages get the overrides too (regardless of whether they use `npm`, `pnpm`, `yarn`, or `bun`).

Does that make sense or is there something else funky going on?

**Comment by ramirezj** [comment]
Let me dig up some examples of where pnpm was complaining (in my morning)

**Comment by jdalton** [comment]
@ramirezj You may be referring to https://github.com/pnpm/pnpm/issues/8740.

**Comment by ramirezj** [comment]
Yes, that was the issue I was seeing, i.e. https://github.com/grendel-consulting/www.grendel-consulting.com/pull/861

**Comment by jdalton** [comment]
Ah okay. In this case it looks like just a needless warning. I'll add it to our documentation as something to be aware of.

**Comment by jdalton** [comment]
Opened PR at https://github.com/pnpm/pnpm/pull/8749 to fix it.
